[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
    "-c",
    "cp assests/img -r $TRUNK_STAGING_DIR/ && cp ./target/stylers/main.css $TRUNK_STAGING_DIR/",
]

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8000
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = true
